### PR TITLE
VF fixes

### PR DESCRIPTION
**Pull request by moyogo**
1. Revert family name to "Exo 2" instead of "Exo2"
   Using the name "Exo2" prevents `gftools qa` from matching with "Exo 2" family on Google Fonts.
2. Use ttfautohint-py installed with python packages (allows pinning version)
3. `sources/build.sh` can be run from another folder.
4. Python packages versions are pinned in the requirements.txt file.
5. Add Github actions to build fonts on push

### CODE REVIEW

**Comment by moyogo** [comment]
@pichotta @djrrb @m4rc1e:

Running Fontbakery on the VF gives 1 FAIL check:
```
 >> com.google.fonts/check/repo/vf_has_static_fonts
    A static fonts directory with at least two fonts must accompany variable fonts
    with vf/Exo2[wght].ttf

      Rationale:
      Variable font family directories kept in the google/fonts git repo must
      include a static/ subdir containing static fonts.
      These files are meant to be served for users that still lack support for
      variable fonts in their web browsers.

    * FAIL: Please create a subdirectory called "static/" and include in it static font files. [code: missing]

    Result: FAIL
```

Should the static fonts be moved to another folder?
Or should this fail be ignored and is the current location of the static font correct?

For the diffenator differences with numerals, the aalt feature has a different orders for alternates. In the before version, the subs is first, it’s further in the order in the after version.
I tried reordering the lookups but that didn’t seem to fix the difference.

**Comment by moyogo** [comment]
Why was the family name changed to "Exo2"?

**Comment by pichotta** [comment]
The family name should reflect what is currently being served on fonts.google.com as noted in the recent fix.

A suggestion was made to follow the folder structure of Oswald. We can verify to accommodate the addition of ufo and instance sources.
https://github.com/googlefonts/OswaldFont

**Comment by m4rc1e** [comment]
That FB check shouldn't be triggered on upstream repos. We have a bug open in fontbakery, https://github.com/googlefonts/fontbakery/issues/2730. We can ignore it.

I'll review the fonts now.

**Pull request merged**
